-- StudySync AI Database Initialization Script

-- 1. Create Profiles Table (Enhanced for Gamification)
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  name text,
  xp integer default 0,
  streak integer default 0,
  level integer default 1,
  total_study_hours numeric default 0,
  achievements jsonb default '[]'::jsonb,
  weeklyStats jsonb default '[]'::jsonb,
  subjectMastery jsonb default '[]'::jsonb,
  stats jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Chat Sessions Table
create table if not exists chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text,
  last_message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Chat Messages Table
create table if not exists chat_messages (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references chat_sessions on delete cascade not null,
 role text not null, -- 'user' or 'model'
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Roadmaps Table
create table if not exists roadmaps (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  topic text not null,
  steps jsonb not null, -- Stores the array of roadmap steps
  progress integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add progress column if it doesn't exist (for existing tables)
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'roadmaps' AND column_name = 'progress') THEN
    ALTER TABLE roadmaps ADD COLUMN progress integer default 0;
  END IF;
END $$;

-- 5. Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table chat_sessions enable row level security;
alter table chat_messages enable row level security;
alter table roadmaps enable row level security;

-- 6. Create Policies (Allow users to manage their own data)
do $$
begin
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can see own profile') then
    create policy "Users can see own profile" on profiles for select using (auth.uid() = id);
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can insert own profile') then
    create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);
  end if;

 if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'chat_sessions' and policyname = 'Users can see own chats') then
    create policy "Users can see own chats" on chat_sessions for select using (auth.uid() = user_id);
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'chat_sessions' and policyname = 'Users can insert own chats') then
    create policy "Users can insert own chats" on chat_sessions for insert with check (auth.uid() = user_id);
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'chat_sessions' and policyname = 'Users can update own chats') then
    create policy "Users can update own chats" on chat_sessions for update using (auth.uid() = user_id);
  end if;

  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'Users can see own messages') then
    create policy "Users can see own messages" on chat_messages for select using (
      exists (select 1 from chat_sessions where id = chat_messages.session_id and user_id = auth.uid())
    );
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'Users can insert own messages') then
    create policy "Users can insert own messages" on chat_messages for insert with check (
      exists (select 1 from chat_sessions where id = chat_messages.session_id and user_id = auth.uid())
    );
  end if;

  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'roadmaps' and policyname = 'Users can see own roadmaps') then
    create policy "Users can see own roadmaps" on roadmaps for select using (auth.uid() = user_id);
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'roadmaps' and policyname = 'Users can insert own roadmaps') then
    create policy "Users can insert own roadmaps" on roadmaps for insert with check (auth.uid() = user_id);
  end if;
  
  if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'roadmaps' and policyname = 'Users can update own roadmaps') then
   create policy "Users can update own roadmaps" on roadmaps for update using (auth.uid() = user_id);
 end if;
 
 if not exists (select * from pg_policies where schemaname = 'public' and tablename = 'roadmaps' and policyname = 'Users can delete own roadmaps') then
   create policy "Users can delete own roadmaps" on roadmaps for delete using (auth.uid() = user_id);
 end if;
end $$;

-- Add missing columns to existing tables if needed

-- Check for missing columns in profiles table
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'profiles' AND column_name = 'total_study_hours') THEN
    ALTER TABLE profiles ADD COLUMN total_study_hours numeric default 0;
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'profiles' AND column_name = 'achievements') THEN
    ALTER TABLE profiles ADD COLUMN achievements jsonb default '[]'::jsonb;
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'profiles' AND column_name = 'weeklyStats') THEN
    ALTER TABLE profiles ADD COLUMN weeklyStats jsonb default '[]'::jsonb;
 END IF;
  IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'profiles' AND column_name = 'subjectMastery') THEN
    ALTER TABLE profiles ADD COLUMN subjectMastery jsonb default '[]'::jsonb;
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'profiles' AND column_name = 'stats') THEN
    ALTER TABLE profiles ADD COLUMN stats jsonb default '{}'::jsonb;
  END IF;
END $$;

-- Check for missing columns in chat_sessions table
DO $$
BEGIN
 IF NOT EXISTS (SELECT FROM information_schema.columns
                 WHERE table_name = 'chat_sessions' AND column_name = 'last_message') THEN
    ALTER TABLE chat_sessions ADD COLUMN last_message text;
  END IF;
END $$;